export const submitParams = {
  "bizCode": "IT",
  "operateType": "build",
  "deliveryAddress": "网易二期",
  "quotationList": [
    {
    	"enquiryAmount": 800,
    	"enquiryCode": "XJ_202106251811190000",
    	"attrs":"{\"颜色\":\"黑\",\"内存\":\"128G\",\"版本\":\"国行\"}",
    	"sku": "1234545",
    	"productName":"手机",
    	"productType":"concept",
    	"brand":"APPLE",
    	"referenceWebSite":"www.baidu.com",
    	"bizCode":"IT",
    	"supplierCode":"11@163.com_0",
    	"supplierName":"张氏",
    	"taxIncludedPrice":1.01,
    	"currency":"CMB",
    	"quoteExpireDate":"2021-06-25 15:19:00",
    	"warrantyInformation": "三年保修",
    	"supplyAmount": 100,
    	"supplyAmountUnit":"个",
    	"arrivalPeriod":"1",
    	"periodUnit":"天",
    	"remark":".....",
    	"attachmentUrl": "11111",
      "tax": "税率"
    }
  ]
}

export const list = {
  "code": "0",
  "msg": "成功",
  "data": {
    "pageNo": 1,
    "pageSize": 10,
    "total": 2,
    "data": [
      {
        "id": 8,
        "enquiryCode": "XJ_202106241625530001",
        "enquiryBatchCode": "B_202106241625530001",
        "enquiryTaskCode": "T_202106211701120001",
        "requestId": "需求单id",
        "requestDetailId": "123456789",
        "bizCode": "IT",
        "ownerUserId": "1332165526370582531",
        "ownerEmail": "zhangjinhui01@corp.netease.com",
        "ownerUserName": "采购人张金辉",
        "enquiryAmount": 800,
        "supplierCode": null,
        "supplierName": null,
        "enquiryType": "online_quotation",
        "urge": false,
        "expireDate": "2021-06-21T12:21:22",
        "status": "overtime",
        "displayStatus": "overtime",
        "displayStatusName": "已失效",
        "remark": "曹贼",
        "createTime": "2021-06-24T16:25:53",
        "updateTime": null,
        "productName": "手机",
        "productType": "concept",
        "brand": "APPLE",
        "attrs": "{\"颜色\":\"黑\",\"内存\":\"128G\",\"版本\":\"国行\"}",
        "referenceWebSite": "www.baidu.com",
        "deliveryAddress": "网易二期",
        "quotation": null
      },
      {
        "id": 7,
        "enquiryCode": "XJ_202106241613270001",
        "enquiryBatchCode": "B_202106241613270001",
        "enquiryTaskCode": "T_202106211701120001",
        "requestId": "需求单id",
        "requestDetailId": "123456789",
        "bizCode": "IT",
        "ownerUserId": "1332165526370582531",
        "ownerEmail": "zhangjinhui01@corp.netease.com",
        "ownerUserName": "采购人张金辉",
        "enquiryAmount": 800,
        "supplierCode": null,
        "supplierName": null,
        "enquiryType": "online_quotation",
        "urge": false,
        "expireDate": "2021-06-21T12:21:22",
        "status": "overtime",
        "displayStatus": "overtime",
        "displayStatusName": "已失效",
        "remark": "曹贼",
        "createTime": "2021-06-24T16:13:27",
        "updateTime": null,
        "productName": "手机",
        "productType": "concept",
        "brand": "APPLE",
        "attrs": "{\"颜色\":\"黑\",\"内存\":\"128G\",\"版本\":\"国行\"}",
        "referenceWebSite": "www.baidu.com",
        "deliveryAddress": "网易二期",
        "quotation": null
      }
    ],
    "count": 1
  }
}



export const historyList = {
  "code": "0",
  "msg": "成功",
  "data": [
    {
      "id": 10,
      "enquiryCode": "XJ_202106242123110001",
      "enquiryBatchCode": "B_202106242123090001",
      "enquiryTaskCode": "T_202106211701120001",
      "requestId": "需求单id",
      "requestDetailId": "123456789",
      "bizCode": "IT",
      "ownerUserId": "1332165526370582531",
      "ownerEmail": "zhangjinhui01@corp.netease.com",
      "ownerUserName": "采购人张金辉",
      "enquiryAmount": 800,
      "supplierCode": null,
      "supplierName": null,
      "enquiryType": "online_quotation",
      "urge": false,
      "expireDate": "2021-06-29T12:21:22",
      "status": "waiting_quotation",
      "displayStatus": "waiting_quotation",
      "displayStatusName": "待报价",
      "remark": "曹贼",
      "createTime": "2021-06-24T21:23:11",
      "updateTime": null,
      "productName": "手机",
      "productType": "concept",
      "brand": "APPLE",
      "attrs": "{\"颜色\":\"黑\",\"内存\":\"128G\",\"版本\":\"国行\"}",
      "referenceWebSite": "www.baidu.com",
      "deliveryAddress": "网易二期",
      "quotation": {
        "id": null,
        "quotationCode": "BJ_202106242141380001",
        "enquiryCode": null,
        "bizCode": null,
        "bizType": null,
        "supplierCode": "xx@163.com_0",
        "supplierName": "张氏",
        "sku": "1234545",
        "productName": "手机",
        "brand": "APPLE",
        "attrs": "{\"颜色\":\"黑\",\"内存\":\"128G\",\"版本\":\"国行\"}",
        "referenceWebSite": null,
        "taxIncludedPrice": 1.01,
        "currency": "CMB",
        "tax": null,
        "quoteExpireDate": "2021-06-25T15:19:00",
        "warrantyInformation": "三年保修",
        "supplyAmount": 100,
        "supplyAmountUnit": null,
        "arrivalPeriod": 1,
        "periodUnit": "天",
        "draft": null,
        "attachmentUrl": "11111",
        "remark": ".....",
        "createTime": "2021-06-24T21:41:38",
        "updateTime": "2021-06-24T21:41:38"
      }
    },
    {
      "id": 9,
      "enquiryCode": "XJ_202106241627410001",
      "enquiryBatchCode": "B_202106241627410001",
      "enquiryTaskCode": "T_202106211701120001",
      "requestId": "需求单id",
      "requestDetailId": "123456789",
      "bizCode": "IT",
      "ownerUserId": "1332165526370582531",
      "ownerEmail": "zhangjinhui01@corp.netease.com",
      "ownerUserName": "采购人张金辉",
      "enquiryAmount": 800,
      "supplierCode": null,
      "supplierName": null,
      "enquiryType": "online_quotation",
      "urge": false,
      "expireDate": "2021-06-29T12:21:22",
      "status": "waiting_confirm",
      "displayStatus": "already_quotation",
      "displayStatusName": "已报价",
      "remark": "曹贼",
      "createTime": "2021-06-24T16:27:41",
      "updateTime": null,
      "productName": "手机",
      "productType": "concept",
      "brand": "APPLE",
      "attrs": "{\"颜色\":\"黑\",\"内存\":\"128G\",\"版本\":\"国行\"}",
      "referenceWebSite": "www.baidu.com",
      "deliveryAddress": "网易二期",
      "quotation": {
        "id": null,
        "quotationCode": "BJ_202106241641070001",
        "enquiryCode": null,
        "bizCode": null,
        "bizType": null,
        "supplierCode": "xx@163.com_1",
        "supplierName": "张氏",
        "sku": "1234545",
        "productName": "手机",
        "brand": "APPLE",
        "attrs": "{\"颜色\":\"黑\",\"内存\":\"128G\",\"版本\":\"国行\"}",
        "referenceWebSite": null,
        "taxIncludedPrice": 1.01,
        "currency": "CMB",
        "tax": null,
        "quoteExpireDate": "2021-06-25T15:19:00",
        "warrantyInformation": "三年保修",
        "supplyAmount": 100,
        "supplyAmountUnit": null,
        "arrivalPeriod": 1,
        "periodUnit": "天",
        "draft": null,
        "attachmentUrl": "11111",
        "remark": ".....",
        "createTime": "2021-06-24T16:41:07",
        "updateTime": "2021-06-24T16:41:07"
      }
    },
    {
      "id": 8,
      "enquiryCode": "XJ_202106241625530001",
      "enquiryBatchCode": "B_202106241625530001",
      "enquiryTaskCode": "T_202106211701120001",
      "requestId": "需求单id",
      "requestDetailId": "123456789",
      "bizCode": "IT",
      "ownerUserId": "1332165526370582531",
      "ownerEmail": "zhangjinhui01@corp.netease.com",
      "ownerUserName": "采购人张金辉",
      "enquiryAmount": 800,
      "supplierCode": null,
      "supplierName": null,
      "enquiryType": "online_quotation",
      "urge": false,
      "expireDate": "2021-06-21T12:21:22",
      "status": "overtime",
      "displayStatus": "overtime",
      "displayStatusName": "已失效",
      "remark": "曹贼",
      "createTime": "2021-06-24T16:25:53",
      "updateTime": null,
      "productName": "手机",
      "productType": "concept",
      "brand": "APPLE",
      "attrs": "{\"颜色\":\"黑\",\"内存\":\"128G\",\"版本\":\"国行\"}",
      "referenceWebSite": "www.baidu.com",
      "deliveryAddress": "网易二期",
      "quotation": null
    },
    {
      "id": 7,
      "enquiryCode": "XJ_202106241613270001",
      "enquiryBatchCode": "B_202106241613270001",
      "enquiryTaskCode": "T_202106211701120001",
      "requestId": "需求单id",
      "requestDetailId": "123456789",
      "bizCode": "IT",
      "ownerUserId": "1332165526370582531",
      "ownerEmail": "zhangjinhui01@corp.netease.com",
      "ownerUserName": "采购人张金辉",
      "enquiryAmount": 800,
      "supplierCode": null,
      "supplierName": null,
      "enquiryType": "online_quotation",
      "urge": false,
      "expireDate": "2021-06-21T12:21:22",
      "status": "overtime",
      "displayStatus": "overtime",
      "displayStatusName": "已失效",
      "remark": "曹贼",
      "createTime": "2021-06-24T16:13:27",
      "updateTime": null,
      "productName": "手机",
      "productType": "concept",
      "brand": "APPLE",
      "attrs": "{\"颜色\":\"黑\",\"内存\":\"128G\",\"版本\":\"国行\"}",
      "referenceWebSite": "www.baidu.com",
      "deliveryAddress": "网易二期",
      "quotation": null
    }
  ]
}

export const brandList = {
  "code": 0,
  "msg": [
    {
      "id": 558,
      "code": "0556",
      "name": "中兴",
      "modifier": "",
      "mt": "",
      "ct": "",
      "delFlag": 0
    },
    {
      "id": 429,
      "code": "0429",
      "name": "中性",
      "modifier": "于振江",
      "mt": 1581405055222,
      "ct": "",
      "delFlag": 0
    },
    {
      "id": 165,
      "code": "0165",
      "name": "中西远大",
      "modifier": "苏佳",
      "mt": 1567741729057,
      "ct": "",
      "delFlag": 0
    }
  ]
}

export const currencyList = {
  code: "0",
  data: 
  [
    {
      "code": "CURRENCY_TYPE",
      "name": "币种",
      "itemCode": "ct_0",
      "itemValue": "元",
      "itemParentCode": null,
      "itemExtA": null,
      "childDictDO": null
    },
    {
      "code": "CURRENCY_TYPE",
      "name": "币种",
      "itemCode": "ct_1",
      "itemValue": "日元",
      "itemParentCode": null,
      "itemExtA": null,
      "childDictDO": null
    },
    {
      "code": "CURRENCY_TYPE",
      "name": "币种",
      "itemCode": "ct_2",
      "itemValue": "港币",
      "itemParentCode": null,
      "itemExtA": null,
      "childDictDO": null
    },
    {
      "code": "CURRENCY_TYPE",
      "name": "币种",
      "itemCode": "ct_3",
      "itemValue": "美元",
      "itemParentCode": null,
      "itemExtA": null,
      "childDictDO": null
    },
    {
      "code": "CURRENCY_TYPE",
      "name": "币种",
      "itemCode": "ct_4",
      "itemValue": "韩元",
      "itemParentCode": null,
      "itemExtA": null,
      "childDictDO": null
    },
    {
      "code": "CURRENCY_TYPE",
      "name": "币种",
      "itemCode": "ct_5",
      "itemValue": "澳元",
      "itemParentCode": null,
      "itemExtA": null,
      "childDictDO": null
    },
    {
      "code": "CURRENCY_TYPE",
      "name": "币种",
      "itemCode": "ct_6",
      "itemValue": "欧元",
      "itemParentCode": null,
      "itemExtA": null,
      "childDictDO": null
    },
    {
      "code": "CURRENCY_TYPE",
      "name": "币种",
      "itemCode": "ct_7",
      "itemValue": "英镑",
      "itemParentCode": null,
      "itemExtA": null,
      "childDictDO": null
    },
    {
      "code": "CURRENCY_TYPE",
      "name": "币种",
      "itemCode": "ct_8",
      "itemValue": "新加坡元",
      "itemParentCode": null,
      "itemExtA": null,
      "childDictDO": null
    },
    {
      "code": "CURRENCY_TYPE",
      "name": "币种",
      "itemCode": "ct_9",
      "itemValue": "加拿大元",
      "itemParentCode": null,
      "itemExtA": null,
      "childDictDO": null
    }
  ],
  msg: "成功"
}
