var dataIndex = {
  pageNum: 1,
  pageSize: 10,
  size: 14,
  total: 14,
  list: [
    {
      projectId: 80958,
      noticeType: "tender",
      noticeTypeName: "招标公告",
      projectName: "杭州网易二园区绿植更换项目",
      applyDeadline: 22829,
      projectStatus: 1,
      projectStatusName: "M2QjPtOTuv",
      publishTime: 1603782248421,
    },
    {
      projectId: 80958,
      noticeType: "tender",
      noticeTypeName: "招标公告",
      projectName: "杭州网易二园区绿植更换项目",
      applyDeadline: 22829,
      projectStatus: 1,
      projectStatusName: "M2QjPtOTuv",
      publishTime: 1603782248421,
    },
    {
      projectId: 80958,
      noticeType: "tender",
      noticeTypeName: "招标公告",
      projectName: "杭州网易二园区绿植更换项目",
      applyDeadline: 22829,
      projectStatus: 1,
      projectStatusName: "M2QjPtOTuv",
      publishTime: 1603782248421,
    },
    {
      projectId: 80958,
      noticeType: "tender",
      noticeTypeName: "招标公告",
      projectName: "杭州网易二园区绿植更换项目",
      applyDeadline: 22829,
      projectStatus: 1,
      projectStatusName: "M2QjPtOTuv",
      publishTime: 1603782248421,
    },
    {
      projectId: 80958,
      noticeType: "tender",
      noticeTypeName: "招标公告",
      projectName: "杭州网易二园区绿植更换项目",
      applyDeadline: 22829,
      projectStatus: 1,
      projectStatusName: "M2QjPtOTuv",
      publishTime: 1603782248421,
    },
    {
      projectId: 80958,
      noticeType: "tender",
      noticeTypeName: "招标公告",
      projectName: "杭州网易二园区绿植更换项目",
      applyDeadline: 22829,
      projectStatus: 1,
      projectStatusName: "M2QjPtOTuv",
      publishTime: 1603782248421,
    },
    {
      projectId: 80958,
      noticeType: "tender",
      noticeTypeName: "招标公告",
      projectName: "杭州网易二园区绿植更换项目",
      applyDeadline: 22829,
      projectStatus: 1,
      projectStatusName: "M2QjPtOTuv",
      publishTime: 1603782248421,
    },
    {
      projectId: 80958,
      noticeType: "tender",
      noticeTypeName: "招标公告",
      projectName: "杭州网易二园区绿植更换项目",
      applyDeadline: 22829,
      projectStatus: 1,
      projectStatusName: "M2QjPtOTuv",
      publishTime: 1603782248421,
    },
    {
      projectId: 78696,
      noticeType: "winning",
      noticeTypeName: "中标公告",
      projectName: "杭州网易二园区绿植更换项目",
      applyDeadline: 11290,
      projectStatus: 2,
      projectStatusName: "nxoqnRmFOZ",
      publishTime: 1603782105061,
    },
    {
      projectId: 92845,
      noticeType: "inquiry",
      noticeTypeName: "询比价公告",
      projectName: "杭州网易二园区绿植更换项目",
      applyDeadline: 39013,
      projectStatus: 3,
      projectStatusName: "wAS7nUjhDn",
      publishTime: 1603782008423,
    },
    {
      projectId: 92845,
      noticeType: "inquiry",
      noticeTypeName: "询比价公告",
      projectName: "杭州网易二园区绿植更换项目",
      applyDeadline: 39013,
      projectStatus: 3,
      projectStatusName: "wAS7nUjhDn",
      publishTime: 1603782008423,
    },
    {
      projectId: 92845,
      noticeType: "inquiry",
      noticeTypeName: "询比价公告",
      projectName: "杭州网易二园区绿植更换项目",
      applyDeadline: 39013,
      projectStatus: 3,
      projectStatusName: "wAS7nUjhDn",
      publishTime: 1603782008423,
    },
    {
      projectId: 92845,
      noticeType: "inquiry",
      noticeTypeName: "询比价公告",
      projectName: "杭州网易二园区绿植更换项目",
      applyDeadline: 39013,
      projectStatus: 3,
      projectStatusName: "wAS7nUjhDn",
      publishTime: 1603782008423,
    },
    {
      projectId: 92845,
      noticeType: "inquiry",
      noticeTypeName: "询比价公告",
      projectName: "杭州网易二园区绿植更换项目",
      applyDeadline: 39013,
      projectStatus: 3,
      projectStatusName: "wAS7nUjhDn",
      publishTime: 1603782008423,
    },
  ],
};

var dataNotice = {
  projectInfo: {
    id: 61252,
    projectType: 32340,
    projectTypeName: "SLwZB8eL24",
    projectName: "杭州网易二园区绿植更换项目",
    bizType: ["92k5IsAMDM", "evkvcWhRCa", "76Q7vCPss6"],
    applyDeadline: 49214,
    tenderNoticeFile: {
      id: 79691,
      fileName: "4xhR3u8pBv",
      fileUrl: "http://paj.kvuswhytmx.ahgx",
    },
    tenderFiles: [
      {
        id: 70563,
        fileName: "zWiHOdxIfq",
        fileUrl: "http://kda.sjtejr.brnw",
      },
      {
        id: 65344,
        fileName: "O4kPDQrG9I",
        fileUrl: "http://dwx.clitswuu.hzul",
      },
      {
        id: 75348,
        fileName: "qUc2D59wol",
        fileUrl: "http://rxv.nrmnmkyj.dtjibe",
      },
    ],
    projectStatus: 94354,
    projectStatusName: "6KXJvTPK6J",
    publishTime: 1603430991934,
    winningFile: {
      fileName: "AaZ3GMO8t8",
      id: 85489,
      fileUrl: "http://zpx.kfhxcchqqkixsx.dznsx",
    },
    winningNoticeTime: 1603431590412,
    winningCompanyNames: [
      "杭州网易绿植有限公司",
      "北京网易绿植有限公司",
      "上海网易绿植有限公司",
      "广州网易绿植有限公司",
    ],
    authority: ["0724VF8W6C", "EkbMe9fXvN", "hjxJq8QK5w"],
  },
  applyInfo: {
    id: 57770,
    projectId: 58461,
    supplierId: 58472,
    applyTime: 1603430308937,
    applyStatus: 8101,
    applyStatusName: "KaDkOwfNHm",
    winningStatus: 83629,
    winningStatusName: "hA6O8JiARU",
    operationInfo: "GyUqcNE04f",
  },
  winningInfo: {
    id: 74550,
    projectId: 75378,
    supplierId: 76099,
    applyTime: 1603430600149,
    applyStatus: 90570,
    applyStatusName: "GGtuQxjBsS",
    winningStatus: 19971,
    winningStatusName: "R7Y40g0S3i",
    operationInfo: "VI71oABBga",
  },
};

const data = { dataIndex, dataNotice };
export default data;
